services:
  # Backend API Service
  - type: web
    name: password-vault-backend
    env: node
    plan: free
    region: oregon
    buildCommand: cd server && chmod +x deploy.sh && ./deploy.sh
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync:
          false # This needs to be set manually in the Render dashboard
          # Make sure to include the database name at the end of your MongoDB URI:
          # mongodb+srv://username:password@cluster.mongodb.net/password_vault
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: password-vault-frontend
    env: node
    plan: free
    region: oregon
    buildCommand: cd client && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://password-vault-backend-o8p4.onrender.com
    autoDeploy: true
