#!/bin/bash

# Enhanced deployment script for the Password Vault backend
# This script helps ensure a smooth deployment on Render

echo "==============================================="
echo "Password Vault Backend Deployment"
echo "==============================================="

# Check for Node.js
echo "Node.js version:"
node --version
npm --version

echo "==============================================="

# Install dependencies
echo "Installing dependencies..."
npm install

# Check for environment variables
echo "Checking environment variables..."
if [ -z "$MONGODB_URI" ]; then
  echo "⚠️ Warning: MONGODB_URI environment variable is not set!"
  echo "   Please set this in the Render dashboard."
  echo "   Make sure to include the database name at the end of your MongoDB URI."
  echo "   Example: mongodb+srv://username:password@cluster.mongodb.net/password_vault"
else
  # Check if URI ends with database name (without exposing the full URI)
  if [[ "$MONGODB_URI" == *"mongodb+srv://"* && "$MONGODB_URI" != *"/"* ]]; then
    echo "⚠️ Warning: Your MongoDB URI might be missing a database name!"
    echo "   A proper URI should end with a database name: mongodb+srv://user:pass@cluster/dbname"
  else
    echo "✅ MONGODB_URI is set"
  fi
fi

if [ -z "$JWT_SECRET" ]; then
  echo "⚠️ Warning: JWT_SECRET environment variable is not set!"
  echo "   This should be automatically generated by Render."
else
  echo "✅ JWT_SECRET is set"
fi

echo "==============================================="
echo "Deployment configuration complete."
echo "Starting server..."
echo "==============================================="

# Server will be started by Render's start command
# No need to start it here